src/main/java/fr/utc/onzzer/client/hmi/main/LoginViewController.java
src/main/java/fr/utc/onzzer/client/hmi/main/MainViewController.java
src/main/resources/fxml/login-view.fxml
src/main/resources/fxml/main-view.fxml

Fixing login view with real login and credentials checks.

Ihmmain users list

---

src/main/java/fr/utc/onzzer/client/data/impl/DataUserServicesImpl.java
src/test/java/fr/utc/onzzer/client/data/DataUserServicesTest.java

Toutes les fonction de l'interface user-data du client sont définis et testées : 
User importProfile(String filePath) throws Exception;
void createProfile(User newClient) throws Exception;
Boolean checkCredentials(String user, String pw) throws Exception;
void exportProfile(User user, String filePath) throws Exception;
User getUser() throws Exception;
void addUser(UserLite userLite) throws Exception;
void setConnectedUsers(final List<UserLite> connectedUsers);
HashMap<UserLite, List<TrackLite>> getConnectedUsers();
void deleteUser(UserLite userLite) throws Exception;
void updateUser(User user) throws Exception;
void deleteAllUsers();

finalisation et test de l'interface Data-User-Client

---

src/main/java/fr/utc/onzzer/client/hmi/main/LoginViewController.java
src/main/java/fr/utc/onzzer/client/hmi/util/ValidationUtil.java

Login is now fully functionnal (missing the import feature, will be done later).

Ihmmain login fix

---

.gitignore
src/main/java/fr/utc/onzzer/client/data/DataTrackServices.java
src/main/java/fr/utc/onzzer/client/data/impl/DataRepository.java
src/main/java/fr/utc/onzzer/client/data/impl/DataTrackServicesImpl.java
src/test/java/fr/utc/onzzer/client/data/DataTrackServicesTest.java

Ajout de l'implémentation de l'interface tracks pour le groupe Data sur le client. Enregistrement des fichiers mp3 dans un dossier tracks (mit dans le gitignore)

implémentation Data-Tracks -1

---

src/main/java/fr/utc/onzzer/client/hmi/main/MainViewController.java
src/main/resources/fxml/main-view.fxml
src/main/resources/styles/main-view.css
src/main/resources/styles/style.css

Fixing the user lists on the main view. The component is now fully functionnal with the search feature.

Ihm main user list v2

---

src/main/java/fr/utc/onzzer/client/hmi/music/DownloadViewController.java
src/main/resources/fxml/download_music.fxml
src/main/resources/styles/style.css

Update download controller and fxml.

Ihmmusic Download Track V2

---

src/main/java/fr/utc/onzzer/client/communication/impl/ClientRequestHandler.java

~ Updated "serverStopped" method to call logOut method from Data

Model clearing when receiving "SERVER_STOPPED" message

---

src/main/resources/fxml/main-view.fxml
src/main/resources/styles/main-view.css

Style buttons

---

src/main/java/fr/utc/onzzer/client/data/DataTrackServices.java
src/main/java/fr/utc/onzzer/client/data/impl/DataTrackServicesImpl.java
src/test/java/client/main/MainController.java
src/test/java/fr/utc/onzzer/client/data/DataTrackServicesTest.java

- Ajout de la track à la liste des track de l'utilisateur
- modification updateTrack et ajout publishTrack
- Ajout fonction deleteTrack
- enregistrement du fichier mp3 dans le dossier tracks
- test et correction de bugs

Data tracks 2

---

src/main/java/fr/utc/onzzer/client/communication/impl/ClientCommunicationController.java

Add a line sending back a USER_PING when received SERVER_PING

User handling for SERVER_PING 

---

src/main/java/fr/utc/onzzer/client/hmi/GlobalController.java
src/main/java/fr/utc/onzzer/client/hmi/main/LoginViewController.java

Fixing socket initialization duplication when logging in.

Ihmmain login fix com init

---

src/main/java/fr/utc/onzzer/client/hmi/music/ListenTrackViewController.java
src/main/resources/fxml/listen-view.fxml

Warning : Squash commit when pull request is accepted !!!!!!!!!!!!!!!!!!!

Ihmmusic listen track

---

src/main/java/fr/utc/onzzer/client/communication/impl/ClientCommunicationController.java
src/main/java/fr/utc/onzzer/client/communication/impl/ClientRequestHandler.java

+ Added handler for "PUBLISH_RATING" message in ClientCommunicationController
+ Added publishRating method in ClientRequestHandler 
~ Updated addRating method in ClientCommunicationController

Added publishRating message handler

---

src/main/java/fr/utc/onzzer/client/communication/impl/ClientCommunicationController.java
src/main/java/fr/utc/onzzer/client/communication/impl/ClientRequestHandler.java

Reverts UTCAI12/onzzer-client#70

Revert "Added publishRating message handler"

---

src/main/java/fr/utc/onzzer/client/data/DataTrackServices.java
src/main/java/fr/utc/onzzer/client/data/impl/DataTrackServicesImpl.java

ajout fonction unPublish et updateTracklite

---

src/main/java/fr/utc/onzzer/client/data/DataTrackServices.java
src/main/java/fr/utc/onzzer/client/data/impl/DataTrackServicesImpl.java
src/test/java/fr/utc/onzzer/client/data/DataTrackServicesTest.java

Ajout fonction publish/ed  / unpublish/ed + maj constructeur DataTrackservice

Dev data track 5

---

.gitignore
src/main/java/fr/utc/onzzer/client/data/impl/DataTrackServicesImpl.java
src/main/java/fr/utc/onzzer/client/data/impl/DataUserServicesImpl.java
src/test/java/fr/utc/onzzer/client/data/DataTrackServicesTest.java
src/test/java/fr/utc/onzzer/client/data/DataUserServicesTest.java

Dev data track tests

---

src/main/java/fr/utc/onzzer/client/data/impl/DataTrackServicesImpl.java

Ajout de la suppressions des fichiers .ser / .mp3

Ajout de la suppressions des fichiers du dossier tracks

---

src/main/java/fr/utc/onzzer/client/hmi/music/UploadViewController.java

fix ihm to server communication when uploading a new track

Fix publish track

---

src/main/java/fr/utc/onzzer/client/communication/impl/ClientCommunicationController.java
src/main/java/fr/utc/onzzer/client/communication/impl/ClientSocketManager.java

Nothing more than remove communcation debug prints

Remove com prints

---

src/main/java/fr/utc/onzzer/client/communication/impl/ClientCommunicationController.java

server side : https://github.com/UTCAI12/onzzer-server/pull/54

using Pair instead of Arraylist in add comment

---

src/main/java/fr/utc/onzzer/client/communication/ComMainServices.java
src/main/java/fr/utc/onzzer/client/communication/ComServicesProvider.java
src/main/java/fr/utc/onzzer/client/communication/impl/ClientCommunicationController.java

~ Replaced "fr.utc.onzzer.common.dataclass.*" imports with specific imports
- Removed unused imports in ComMainServices
- Removed unused imports in ComServicesProvider

Cleared imports in communication classes

---

src/main/java/fr/utc/onzzer/client/hmi/main/MyTrackController.java

Adding track event listening for the track list.

Ihmmain tracklist event listening

---

src/main/java/fr/utc/onzzer/client/communication/impl/ClientRequestHandler.java

~ Updated userDisconnect method in ClientRequestHandler (using removeUser method from dataServicesProvider instead of deleteUser)

Fixed profile deletion after disconnection

---

src/main/java/fr/utc/onzzer/client/communication/impl/ClientRequestHandler.java

~ Updated receiveTrack method (removed calls to addTrackToLibrary and updateTrack, and replaced them by a saveTrack call)

Fixed track download issue

---

src/main/java/fr/utc/onzzer/client/data/impl/DataTrackServicesImpl.java
src/main/java/fr/utc/onzzer/client/data/impl/DataUserServicesImpl.java

Issues #119 et #127
Pour les répertoire de musique par utilisateur j'ai ajouté la lecture des fichiers dans la fonction checkCredentials qui permet de login un user, et j'ai commenté dans le constructeur de la classe DataTrackService la lecture des fichier (car l'utilisateur n'est pas encore connecté)
J'ai fais les test unitaire mais pas de test fonctionnel

Dev data issues
